# -*- coding: utf-8 -*-
"""Projet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aqpuEO20gIoDXeDo4pffjFN0sPJfPQhW
"""

import pandas as pd

train_df = pd.read_csv("data/train.csv")

print(train_df.head())

print("Colonnes:", list(train_df.columns))

print("Nb docs train:", len(train_df))

counts = train_df["type"].value_counts()
print(counts)

"""La classe la plus fréquente est Plat principal."""

print("proportions")
print(counts / len(train_df))

print("Longueur moyenne des recettes")
train_df["rec_words"] = train_df["recette"].fillna("").astype(str).str.split().str.len()
train_df["rec_chars"] = train_df["recette"].fillna("").astype(str).str.len()
print(train_df[["rec_words", "rec_chars"]].mean())

print(" Analyse du déséquilibre")
print("Ratio max/min =", counts.max() / counts.min() )

"""La classe la plus grande (“Plat principal”) est environ 2 fois la plus petite (“Entrée”)."""