# -*- coding: utf-8 -*-
"""Projet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aqpuEO20gIoDXeDo4pffjFN0sPJfPQhW
"""

import pandas as pd

train_df = pd.read_csv("data/train.csv")

print(train_df.head())

print("Colonnes:", list(train_df.columns))

print("Nb docs train:", len(train_df))

counts = train_df["type"].value_counts()
print(counts)

"""La classe la plus fréquente est Plat principal."""

print("proportions")
print(counts / len(train_df))

print("Longueur moyenne des recettes")
train_df["rec_words"] = train_df["recette"].fillna("").astype(str).str.split().str.len()
train_df["rec_chars"] = train_df["recette"].fillna("").astype(str).str.len()
print(train_df[["rec_words", "rec_chars"]].mean())

print(" Analyse du déséquilibre")
print("Ratio max/min =", counts.max() / counts.min() )

"""La classe la plus grande (“Plat principal”) est environ 2 fois la plus petite (“Entrée”)."""

methode_B = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=2, max_df=0.95)),
    ("clf", LinearSVC())
])

scores_B = cross_validate(
    methode_B, X, y, cv=cv,
    scoring={"micro_f1":"f1_micro", "macro_f1":"f1_macro", "acc":"accuracy"}
)

print("\nMéthode B (TF-IDF 1-2 grams + LinearSVC):")
for m in ["test_micro_f1", "test_macro_f1", "test_acc"]:
    print(m, scores_B[m].mean())